#!/bin/bash

# Flight Remote Installer
# curl -fsSL https://raw.githubusercontent.com/mojoatomic/flight/main/install.sh | bash

set -e

REPO="mojoatomic/flight"
BRANCH="main"
BASE_URL="https://raw.githubusercontent.com/$REPO/$BRANCH"

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    Flight Installation                        ║"
echo "║        TDD-style prompt engineering for Claude Code           ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

# Create directory structure
echo "📁 Creating directory structure..."
mkdir -p .flight/domains
mkdir -p .claude/commands

# Download core files
echo "📄 Downloading Flight files..."

curl -fsSL "$BASE_URL/CLAUDE.md" -o CLAUDE.md
echo "   ✓ CLAUDE.md"

curl -fsSL "$BASE_URL/.flight/FLIGHT.md" -o .flight/FLIGHT.md 2>/dev/null && echo "   ✓ .flight/FLIGHT.md" || true

# Download domain files
for domain in embedded-c-p10 javascript react rp2040-pico; do
    curl -fsSL "$BASE_URL/.flight/domains/${domain}.md" -o ".flight/domains/${domain}.md" 2>/dev/null && echo "   ✓ domains/${domain}.md" || true
done

# Download validation scripts
for domain in embedded-c-p10 javascript; do
    curl -fsSL "$BASE_URL/.flight/domains/${domain}.validate.sh" -o ".flight/domains/${domain}.validate.sh" 2>/dev/null && chmod +x ".flight/domains/${domain}.validate.sh" && echo "   ✓ domains/${domain}.validate.sh" || true
done

# Download slash commands
for cmd in flight-prime flight-compile flight-validate flight-tighten flight-check; do
    curl -fsSL "$BASE_URL/.claude/commands/${cmd}.md" -o ".claude/commands/${cmd}.md" 2>/dev/null && echo "   ✓ commands/${cmd}.md" || true
done

# Create PROMPT.md if missing
if [ ! -f "PROMPT.md" ]; then
    cat > PROMPT.md << 'EOF'
# Task Prompt

Use `/flight-prime` to research, then `/flight-compile` to build this file.

---
*Auto-generated by Flight*
EOF
    echo "   ✓ PROMPT.md"
fi

# Create @fix_plan.md if missing
if [ ! -f "@fix_plan.md" ]; then
    cat > @fix_plan.md << 'EOF'
# Fix Plan

## Current Priority
- [ ] Initial setup

## Backlog

## Completed
EOF
    echo "   ✓ @fix_plan.md"
fi

echo ""
echo "✅ Flight installed!"
echo ""
echo "Commands:"
echo "  /flight-prime     - Research task and context"
echo "  /flight-compile   - Build PROMPT.md"
echo "  /flight-validate  - Run domain validation scripts"
echo "  /flight-tighten   - Strengthen rules on failure"
echo ""
echo "Validation scripts:"
ls -1 .flight/domains/*.validate.sh 2>/dev/null | sed 's/.*\//  /' || echo "  (none)"
echo ""
echo "Run: /flight-prime \"your task here\" to get started"
echo ""
