#!/bin/bash
# javascript.validate.sh - Code quality patterns that prevent common mistakes in JavaScript/Node
# Generated by flight-domain-compile from javascript.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="**/*.js **/*.mjs **/*.cjs"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        printf '%s\n' "$result" | head -10 | sed 's/^/   /'
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        printf '%s\n' "$result" | head -5 | sed 's/^/   /'
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  JAVASCRIPT Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "*.js" "*.mjs" "*.cjs")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    mapfile -t FILES < <(find . -type f \( -name "*.js" -o -name "*.mjs" -o -name "*.cjs" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: **/*.js **/*.mjs **/*.cjs..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: Generic Variable Names
check "N1: Generic Variable Names" \
    grep -En "\\b(const|let|var)\\s+(data|result|temp|info|item|value|obj|thing|stuff|tmp|ret|val)\\s*=" "${FILES[@]}"

# N2: Redundant Conditional Returns
check "N2: Redundant Conditional Returns" \
    grep -En "return true;?\\s*(else|})?\\s*return false|return false;?\\s*(else|})?\\s*return true" "${FILES[@]}"

# N3: Ternary Returning Boolean Literals
check "N3: Ternary Returning Boolean Literals" \
    grep -En "\\?\\s*true\\s*:\\s*false|\\?\\s*false\\s*:\\s*true" "${FILES[@]}"

# N4: Redundant Boolean Comparisons
check "N4: Redundant Boolean Comparisons" \
    grep -En "===\\s*true|===\\s*false|!==\\s*true|!==\\s*false" "${FILES[@]}"

# N5: Magic Number Calculations
check "N5: Magic Number Calculations" \
    grep -En "[0-9]+\\s*\\*\\s*[0-9]+\\s*\\*\\s*[0-9]+" "${FILES[@]}"

# N6: Generic Function Names
check "N6: Generic Function Names" \
    grep -En "function\\s+(handle|process|do|run|execute|manage)(Data|Item|Value|Info|Result|Object)\\s*\\(" "${FILES[@]}"

# N7: Single-Letter Variables
check "N7: Single-Letter Variables" \
    grep -En "\\b(const|let|var)\\s+[a-hln-z]\\s*=" "${FILES[@]}"

# N8: console.log in Source Files
check "N8: console.log in Source Files" \
    bash -c 'for f in "$@"; do
  if [[ "$f" != *test* ]] && [[ "$f" != *spec* ]]; then
    grep -n '"'"'console\.log'"'"' "$f" 2>/dev/null
  fi
done' _ "${FILES[@]}"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
