#!/usr/bin/env bash
# javascript.validate.sh - Code quality patterns that prevent common mistakes in JavaScript/Node
# Generated by flight-domain-compile from javascript.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="**/*.js **/*.mjs **/*.cjs"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        printf '%s\n' "$result" | head -10 | sed 's/^/   /'
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        printf '%s\n' "$result" | head -5 | sed 's/^/   /'
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  JAVASCRIPT Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "*.js" "*.mjs" "*.cjs")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    mapfile -t FILES < <(find . -type f \( -name "*.js" -o -name "*.mjs" -o -name "*.cjs" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: **/*.js **/*.mjs **/*.cjs..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: Generic Variable Names
check "N1: Generic Variable Names" \
    # Unknown check type: ast

# N2: Redundant Conditional Returns
check "N2: Redundant Conditional Returns" \
    # Unknown check type: ast

# N3: Ternary Returning Boolean Literals
check "N3: Ternary Returning Boolean Literals" \
    # Unknown check type: ast

# N4: Redundant Boolean Comparisons
check "N4: Redundant Boolean Comparisons" \
    # Unknown check type: ast

# N5: Magic Number Calculations
check "N5: Magic Number Calculations" \
    # Unknown check type: ast

# N6: Generic Function Names
check "N6: Generic Function Names" \
    # Unknown check type: ast

# N7: Single-Letter Variables
check "N7: Single-Letter Variables" \
    # Unknown check type: ast

# N8: console.log in Source Files
check "N8: console.log in Source Files" \
    # Unknown check type: ast

# N9: var Declaration
check "N9: var Declaration" \
    # Unknown check type: ast

# N10: Loose Equality
check "N10: Loose Equality" \
    # Unknown check type: ast

printf '\n%s\n' "## SHOULD Rules"

# S1: Await in Loops
warn "S1: Await in Loops" \
    # Unknown check type: ast

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
