#!/usr/bin/env bash
# kubernetes.validate.sh - Kubernetes YAML manifest best practices
# Generated by flight-domain-compile from kubernetes.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="**/*.yaml **/*.yml"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -10 | sed 's/^/   /') || true
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -5 | sed 's/^/   /') || true
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  KUBERNETES Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "*.yaml" "*.yml")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    # Redirect stdin from /dev/null to prevent hanging in piped contexts (curl | bash)
    mapfile -t FILES < <(find . -type f \( -name "*.yaml" -o -name "*.yml" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" < /dev/null 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: **/*.yaml **/*.yml..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: Privileged Containers
check "N1: Privileged Containers" \
    grep -Ein "privileged:\\s*true" "${FILES[@]}"

# N2: Host Namespace Sharing
check "N2: Host Namespace Sharing" \
    grep -Ein "host(PID|IPC|Network):\\s*true" "${FILES[@]}"

# N3: Dangerous Capabilities
check "N3: Dangerous Capabilities" \
    grep -Eiz "capabilities:[\\s\\S]*?add:[\\s\\S]*?(SYS_ADMIN|NET_ADMIN|SYS_PTRACE|NET_RAW|SYS_MODULE|DAC_READ_SEARCH|ALL)\\b" "${FILES[@]}"

# N4: HostPath Volume Mounts
check "N4: HostPath Volume Mounts" \
    grep -Ein "hostPath:" "${FILES[@]}"

# N5: Privilege Escalation Allowed
check "N5: Privilege Escalation Allowed" \
    grep -En "allowPrivilegeEscalation:\\s*true" "${FILES[@]}"

# N6: Running as Root User
check "N6: Running as Root User" \
    grep -En "runAsUser:\\s*0\\s*\$" "${FILES[@]}"

# N7: Secrets in Environment Variables
check "N7: Secrets in Environment Variables" \
    grep -Eiz "name:\\s*(PASSWORD|SECRET|API_KEY|TOKEN|PRIVATE_KEY|CREDENTIAL|AUTH_TOKEN)\\s*\\n\\s*value:\\s*[\"\\x27]?[^\"\\x27\\n]+" "${FILES[@]}"

printf '\n%s\n' "## MUST Rules"

# M1: Container Image Tag Required
check "M1: Container Image Tag Required" \
    bash -c '(grep -En "image:\\s*[\"\\x27]?[a-zA-Z0-9._/-]+(:latest)?\\s*[\"\\x27]?\\s*\$" "$@" | grep -v ":[0-9]" | grep -v "@sha256:") || true' _ "${FILES[@]}"

printf '\n%s\n' "## Info"

DEPLOYMENT_COUNT=$( (grep -cE "kind:\s*Deployment" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Deployments: %s\n' "$DEPLOYMENT_COUNT"

STATEFULSET_COUNT=$( (grep -cE "kind:\s*StatefulSet" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  StatefulSets: %s\n' "$STATEFULSET_COUNT"

SERVICE_COUNT=$( (grep -cE "kind:\s*Service" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Services: %s\n' "$SERVICE_COUNT"

CONFIGMAP_COUNT=$( (grep -cE "kind:\s*ConfigMap" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  ConfigMaps: %s\n' "$CONFIGMAP_COUNT"

SECRET_COUNT=$( (grep -cE "kind:\s*Secret" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Secrets: %s\n' "$SECRET_COUNT"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
