#!/usr/bin/env bash
# nextjs.validate.sh - Next
# Generated by flight-domain-compile from nextjs.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="app/**/*.tsx app/**/*.ts app/*.tsx app/*.ts"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -10 | sed 's/^/   /') || true
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -5 | sed 's/^/   /') || true
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  NEXTJS Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "*.tsx" "*.ts")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    # Redirect stdin from /dev/null to prevent hanging in piped contexts (curl | bash)
    mapfile -t FILES < <(find . -type f \( -name "*.tsx" -o -name "*.ts" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" < /dev/null 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: app/**/*.tsx app/**/*.ts app/*.tsx app/*.ts..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: 'use client' in page.tsx Files
# Path filtering for this rule
FILTERED_FILES=()
for __f in "${FILES[@]}"; do
    if ! ( [[ "$__f" == *page.tsx ]] ); then continue; fi
    FILTERED_FILES+=("$__f")
done
if [[ ${#FILTERED_FILES[@]} -gt 0 ]]; then
    check "N1: 'use client' in page.tsx Files" \
        grep -En "^['\"]use client['\"]" "${FILTERED_FILES[@]}"
else
    green "✅ N1: 'use client' in page.tsx Files (skipped - no matching files after path filter)"
    ((PASS++)) || true
fi

# N2: React Hooks in Server Components
check "N2: React Hooks in Server Components" \
    bash -c '
for f in "$@"; do
    trigger_lines=$(grep -nE "useState|useEffect|useRef|useCallback|useMemo|useReducer" "$f" 2>/dev/null)
    if [[ -n "$trigger_lines" ]]; then
        if ! grep -qE "'"'"'use client'"'"'|\"use client\"" "$f" 2>/dev/null; then
            echo "$trigger_lines" | while IFS= read -r line; do
                linenum="${line%%:*}"
                echo "$f:$linenum: has hooks but no '"'"'use client'"'"'"
            done
        fi
    fi
done
' _ "${FILES[@]}"

# N3: useEffect Fetch for Initial Page Data
check "N3: useEffect Fetch for Initial Page Data" \
    # Unknown check type: ast

# N5: 'any' Type in Route Handlers
# Path filtering for this rule
FILTERED_FILES=()
for __f in "${FILES[@]}"; do
    if ! ( [[ "$__f" == *route.ts ]] ); then continue; fi
    FILTERED_FILES+=("$__f")
done
if [[ ${#FILTERED_FILES[@]} -gt 0 ]]; then
    check "N5: 'any' Type in Route Handlers" \
        grep -En ": any" "${FILTERED_FILES[@]}"
else
    green "✅ N5: 'any' Type in Route Handlers (skipped - no matching files after path filter)"
    ((PASS++)) || true
fi

# N6: Hardcoded Multi-segment Routes
check "N6: Hardcoded Multi-segment Routes" \
    # Unknown check type: ast

# N7: console.log in App Directory
check "N7: console.log in App Directory" \
    # Unknown check type: ast

printf '\n%s\n' "## SHOULD Rules"

# S1: Dynamic Routes Should Use notFound()
# Path filtering for this rule
FILTERED_FILES=()
for __f in "${FILES[@]}"; do
    if ! ( [[ "$__f" == *]*/page.tsx ]] || [[ "$__f" == *]/page.tsx ]] ); then continue; fi
    FILTERED_FILES+=("$__f")
done
if [[ ${#FILTERED_FILES[@]} -gt 0 ]]; then
    warn "S1: Dynamic Routes Should Use notFound()" \
        bash -c '
for f in "$@"; do
    if ! grep -qE "notFound" "$f" 2>/dev/null; then
        echo "$f: dynamic route without notFound()"
    fi
done
' _ "${FILTERED_FILES[@]}"
else
    green "✅ S1: Dynamic Routes Should Use notFound() (skipped - no matching files after path filter)"
    ((PASS++)) || true
fi

printf '\n%s\n' "## Info"

SERVER_COMPONENTS=$( (grep -rL "'use client'|"use client"" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Server components: %s\n' "$SERVER_COMPONENTS"

CLIENT_COMPONENTS=$( (grep -rl "'use client'|"use client"" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Client components: %s\n' "$CLIENT_COMPONENTS"

ROUTE_HANDLERS=$( (grep -E "route\.ts$" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Route handlers: %s\n' "$ROUTE_HANDLERS"

SERVER_ACTIONS=$( (grep -rl "'use server'" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Server action files: %s\n' "$SERVER_ACTIONS"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
