#!/bin/bash
# rp2040-pico.validate.sh - Raspberry Pi Pico (RP2040) dual-core embedded development with Pico SDK
# Generated by flight-domain-compile from rp2040-pico.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="src/**/*.c src/**/*.h src/*.c src/*.h"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        printf '%s\n' "$result" | head -10 | sed 's/^/   /'
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        printf '%s\n' "$result" | head -5 | sed 's/^/   /'
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  RP2040-PICO Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "*.c" "*.h")
else
    # Fallback: glob expansion without exclusions
    shopt -s nullglob globstar
    FILES=($DEFAULT_PATTERNS)
    shopt -u nullglob globstar
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: src/**/*.c src/**/*.h src/*.c src/*.h..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: No malloc/free
check "N1: No malloc/free" \
    grep -En "\\bmalloc\\s*\\(|\\bfree\\s*\\(|\\bcalloc\\s*\\(|\\brealloc\\s*\\(" "${FILES[@]}"

# N2: No printf in Interrupt Handlers
check "N2: No printf in Interrupt Handlers" \
    bash -c 'for f in "$@"; do
  awk '"'"'/void.*(_callback|_isr|_handler|_irq)\s*\(/,/^\}/ { if (/printf|puts|print/) print FILENAME":"NR": "$0 }'"'"' "$f"
done' _ "${FILES[@]}"

# N3: No Recursive Functions
check "N3: No Recursive Functions" \
    bash -c 'for f in "$@"; do
  awk '"'"'/^[a-zA-Z_][a-zA-Z0-9_]*\s+[a-zA-Z_][a-zA-Z0-9_]*\s*\(/ {
    match($0, /([a-zA-Z_][a-zA-Z0-9_]*)\s*\(/, arr)
    if (arr[1] != "") fname = arr[1]
  }
  fname && $0 ~ fname"\\s*\\(" && !/^[a-zA-Z_]/ {
    print FILENAME":"NR": possible recursion in "fname
  }'"'"' "$f" 2>/dev/null
done | head -5' _ "${FILES[@]}"

# N4: No Direct Register Access
check "N4: No Direct Register Access" \
    bash -c 'grep -En '"'"'\*\s*\(volatile\s+uint32_t\s*\*\)|0x[0-9a-fA-F]+\s*='"'"' "$@" | grep -v '"'"'#define'"'"'' _ "${FILES[@]}"

# N5: I2C/SPI Must Use Timeout Versions
check "N5: I2C/SPI Must Use Timeout Versions" \
    bash -c 'for f in "$@"; do
  grep -En '"'"'i2c_write_blocking\(|i2c_read_blocking\(|spi_write_blocking\(|spi_read_blocking\('"'"' "$f" 2>/dev/null | \
  grep -v '"'"'timeout'"'"' | head -5
done' _ "${FILES[@]}"

# N6: Arrays Must Have Named Size Constants
check "N6: Arrays Must Have Named Size Constants" \
    bash -c 'for f in "$@"; do
  grep -En '"'"'\[[0-9]+\]'"'"' "$f" 2>/dev/null | grep -v '"'"'#define\|//\|/\*'"'"' | head -5
done' _ "${FILES[@]}"

# N7: Core 0 Must Use Watchdog
check "N7: Core 0 Must Use Watchdog" \
    bash -c 'for f in "$@"; do
  if echo "$f" | grep -q '"'"'main\.c'"'"'; then
    if ! grep -q '"'"'watchdog_enable\|watchdog_update'"'"' "$f"; then
      echo "$f: missing watchdog"
    fi
  fi
done' _ "${FILES[@]}"

printf '\n%s\n' "## SHOULD Rules"

# S1: Review Blocking Calls in Safety/Core0 Files
warn "S1: Review Blocking Calls in Safety/Core0 Files" \
    bash -c 'for f in "$@"; do
  if echo "$f" | grep -qiE '"'"'main\.c|safety|core0'"'"'; then
    grep -En '"'"'sleep_ms|_blocking\(|while\s*\(\s*true|for\s*\(\s*;\s*;\s*\)'"'"' "$f" 2>/dev/null | head -5
  fi
done' _ "${FILES[@]}"

# S2: Review Float/Double in Safety Files
warn "S2: Review Float/Double in Safety Files" \
    bash -c 'for f in "$@"; do
  if echo "$f" | grep -qiE '"'"'safety|emergency|watchdog|core0'"'"'; then
    grep -En '"'"'\bfloat\b|\bdouble\b'"'"' "$f" 2>/dev/null
  fi
done' _ "${FILES[@]}"

# S3: Review Unbounded Loops
warn "S3: Review Unbounded Loops" \
    grep -En "while\\s*\\(\\s*1\\s*\\)|while\\s*\\(\\s*true\\s*\\)|for\\s*\\(\\s*;\\s*;\\s*\\)" "${FILES[@]}"

# S4: Multicore Launch Should Have Handshake
warn "S4: Multicore Launch Should Have Handshake" \
    bash -c 'for f in "$@"; do
  if grep -q '"'"'multicore_launch_core1'"'"' "$f"; then
    if ! grep -q '"'"'multicore_fifo_pop\|multicore_fifo_push'"'"' "$f"; then
      echo "$f: multicore launch without FIFO handshake"
    fi
  fi
done' _ "${FILES[@]}"

# S5: Shared Volatile State Should Use Spinlocks
warn "S5: Shared Volatile State Should Use Spinlocks" \
    bash -c 'for f in "$@"; do
  if grep -q '"'"'volatile.*g_\|static.*volatile'"'"' "$f"; then
    if ! grep -q '"'"'spin_lock\|spinlock'"'"' "$f"; then
      echo "$f: has volatile globals but no spinlock"
    fi
  fi
done' _ "${FILES[@]}"

# S6: Functions With Pointer Params Should ASSERT Non-null
warn "S6: Functions With Pointer Params Should ASSERT Non-null" \
    bash -c 'for f in "$@"; do
  awk '"'"'
  /^[a-zA-Z_].*\*[a-zA-Z_]+\)/ {
    func_line = NR; has_ptr = 1
  }
  has_ptr && NR <= func_line + 5 && /ASSERT.*!=.*NULL|assert.*!=.*NULL/ {
    has_ptr = 0
  }
  has_ptr && NR > func_line + 5 && /^\{/ {
    print FILENAME":"func_line": function with pointer param missing ASSERT"
    has_ptr = 0
  }
  '"'"' "$f" 2>/dev/null
done | head -5' _ "${FILES[@]}"

# S7: Status Return Values Should Be Checked
warn "S7: Status Return Values Should Be Checked" \
    bash -c 'for f in "$@"; do
  grep -En '"'"'^\s+[a-z_]+\s*\([^;]*\)\s*;'"'"' "$f" 2>/dev/null | \
  grep -v '"'"'if\s*(\|=\s*\|void\|return'"'"' | head -5
done' _ "${FILES[@]}"

# S8: Should Have Dual-Core Structure
warn "S8: Should Have Dual-Core Structure" \
    bash -c 'missing=""
if ! ls "$@" 2>/dev/null | grep -q '"'"'main\.c'"'"'; then
  missing="Missing main.c (Core 0 entry)"
fi
if ! ls "$@" 2>/dev/null | grep -qE '"'"'core1\.c|core_1\.c'"'"'; then
  if [ -n "$missing" ]; then
    echo "$missing"
  fi
  echo "Missing core1.c (Core 1 entry)"
elif [ -n "$missing" ]; then
  echo "$missing"
fi' _ "${FILES[@]}"

# S9: Should Have Emergency Handling
warn "S9: Should Have Emergency Handling" \
    bash -c 'if ! grep -rl '"'"'emergency\|EMERGENCY'"'"' "$@" 2>/dev/null | head -1 | grep -q '"'"'.'"'"'; then
  echo "No emergency handling found"
fi' _ "${FILES[@]}"

# S10: Should Have Inter-Core Heartbeat
warn "S10: Should Have Inter-Core Heartbeat" \
    bash -c 'if ! grep -rl '"'"'heartbeat\|HEARTBEAT'"'"' "$@" 2>/dev/null | head -1 | grep -q '"'"'.'"'"'; then
  echo "No heartbeat mechanism found"
fi' _ "${FILES[@]}"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
