#!/usr/bin/env bash
# supabase.validate.sh - Supabase patterns for TypeScript/Next
# Generated by flight-domain-compile from supabase.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="**/*.ts **/*.tsx"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -10 | sed 's/^/   /') || true
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -5 | sed 's/^/   /') || true
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  SUPABASE Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "*.ts" "*.tsx")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    # Redirect stdin from /dev/null to prevent hanging in piped contexts (curl | bash)
    mapfile -t FILES < <(find . -type f \( -name "*.ts" -o -name "*.tsx" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" < /dev/null 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: **/*.ts **/*.tsx..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: service_role Key in Client Code
check "N1: service_role Key in Client Code" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  # Check for service_role in any client-accessible file
  # Skip files that are clearly server-only (api/, server/, actions/)
  if [[ "$f" != *"/api/"* ]] && [[ "$f" != *"/server/"* ]] && [[ "$f" != *".server."* ]] && [[ "$f" != *"/actions/"* ]]; then
    grep -HnE '"'"'service_role|SERVICE_ROLE'"'"' "$f" 2>/dev/null
  fi
done
done' _ "${FILES[@]}"

# N2: Deprecated @supabase/auth-helpers-nextjs
check "N2: Deprecated @supabase/auth-helpers-nextjs" \
    # Unknown check type: ast

# N3: Raw @supabase/supabase-js in Next.js App Router
check "N3: Raw @supabase/supabase-js in Next.js App Router" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  # Only flag if it'"'"'s importing createClient from supabase-js directly
  # AND it looks like a Next.js app (has '"'"'use client'"'"' or next imports)
  if grep -q "from ['"'"'\"]@supabase/supabase-js['"'"'\"]" "$f" 2>/dev/null; then
    if grep -qE "'"'"'use client'"'"'|\"use client\"|from ['"'"'\"]next" "$f" 2>/dev/null; then
      grep -Hn "from ['"'"'\"]@supabase/supabase-js['"'"'\"]" "$f"
    fi
  fi
done
done' _ "${FILES[@]}"

# N4: Hardcoded Supabase Credentials
check "N4: Hardcoded Supabase Credentials" \
    # Unknown check type: ast

# N5: .single() Without Error Handling
check "N5: .single() Without Error Handling" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  # Find .single() calls that don'"'"'t have error handling nearby
  awk '"'"'
  /\.single\(\)/ {
    # Check if this line or next few lines have error handling
    line = $0
    getline next1
    getline next2
    combined = line next1 next2
    if (combined !~ /error|Error|catch|PGRST|throw|if.*!|\.maybeSingle/) {
      print FILENAME":"NR": "$0
    }
  }
  '"'"' "$f" 2>/dev/null
done
done' _ "${FILES[@]}"

# N6: Realtime Subscription Without Cleanup
check "N6: Realtime Subscription Without Cleanup" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  # Find files with realtime subscriptions
  if grep -q "\.channel\|\.on.*postgres_changes\|\.subscribe()" "$f" 2>/dev/null; then
    # Check if there'"'"'s cleanup (removeChannel, unsubscribe, or cleanup return)
    if ! grep -qE "removeChannel|\.unsubscribe\(\)|return.*=>.*remove|return.*\(\).*=>|cleanup" "$f" 2>/dev/null; then
      echo "$f: realtime subscription without cleanup"
    fi
  fi
done
done' _ "${FILES[@]}"

# N7: getSession() in Server Code for Auth Checks
check "N7: getSession() in Server Code for Auth Checks" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  # Check server files (api routes, server components, middleware)
  if [[ "$f" == *"/api/"* ]] || [[ "$f" == *".server."* ]] || [[ "$f" == *"middleware"* ]] || [[ "$f" == *"/actions/"* ]]; then
    # Flag getSession used for auth decisions without getClaims/getUser
    if grep -q "getSession" "$f" 2>/dev/null; then
      if ! grep -qE "getClaims|getUser" "$f" 2>/dev/null; then
        grep -Hn "getSession" "$f"
      fi
    fi
  fi
done
done' _ "${FILES[@]}"

printf '\n%s\n' "## MUST Rules"

# M1: Type Database Schema
check "M1: Type Database Schema" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  # Find createBrowserClient or createServerClient without type param
  grep -En "create(Browser|Server)Client\([^<]*\)" "$f" 2>/dev/null | \
    grep -v "<Database>" | head -3
done
done' _ "${FILES[@]}"

# M2: Handle Auth State Changes
check "M2: Handle Auth State Changes" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  # Find client files that use auth but don'"'"'t have onAuthStateChange
  if grep -q "'"'"'use client'"'"'" "$f" 2>/dev/null; then
    if grep -qE "supabase\.auth\.(getUser|getSession|signIn|signOut)" "$f" 2>/dev/null; then
      if ! grep -q "onAuthStateChange" "$f" 2>/dev/null; then
        echo "$f: uses auth without onAuthStateChange listener"
      fi
    fi
  fi
done
done' _ "${FILES[@]}"

printf '\n%s\n' "## Info"

SUPABASE_IMPORTS=$( (grep -oE "from .@supabase" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Supabase imports: %s\n' "$SUPABASE_IMPORTS"

REALTIME_SUBSCRIPTIONS=$( (grep -cE "\.channel\(|\.on.*postgres_changes" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Realtime subscriptions: %s\n' "$REALTIME_SUBSCRIPTIONS"

AUTH_CALLS=$( (grep -cE "supabase\.auth\." "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  Auth API calls: %s\n' "$AUTH_CALLS"

SINGLE_CALLS=$( (grep -cE "\.single\(\)" "${FILES[@]}" 2>/dev/null || true) | awk -F: '{s+=$NF}END{print s+0}')
printf 'ℹ️  .single() calls: %s\n' "$SINGLE_CALLS"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
