#!/usr/bin/env bash
# testing.validate.sh - Universal unit test patterns
# Generated by flight-domain-compile from testing.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="**/*test*.js **/*spec*.js **/*_test.py **/test_*.py **/*_test.go **/Test*.java"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        printf '%s\n' "$result" | head -10 | sed 's/^/   /'
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        printf '%s\n' "$result" | head -5 | sed 's/^/   /'
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  TESTING Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "*test*.js" "*spec*.js" "*_test.py" "test_*.py" "*_test.go" "Test*.java")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    mapfile -t FILES < <(find . -type f \( -name "*test*.js" -o -name "*spec*.js" -o -name "*_test.py" -o -name "test_*.py" -o -name "*_test.go" -o -name "Test*.java" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: **/*test*.js **/*spec*.js **/*_test.py **/test_*.py **/*_tes..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: Enumerated Test Names
check "N1: Enumerated Test Names" \
    grep -En "test\\(['\"]test[0-9]|it\\(['\"][0-9]|def test[0-9]+|func Test[0-9]+\\(" "${FILES[@]}"

# N2: Empty Test Bodies
check "N2: Empty Test Bodies" \
    grep -En "it\\([^)]+,\\s*\\(\\)\\s*=>\\s*\\{\\s*\\}\\)|it\\(['\"]['\"],|def test[^:]+:\\s*pass\$|func Test[^{]+\\{\\s*\\}|@Test[^{]+\\{\\s*\\}" "${FILES[@]}"

# N3: Hardcoded Sleep/Delays
check "N3: Hardcoded Sleep/Delays" \
    grep -En "sleep\\s*\\(|time\\.sleep|Thread\\.sleep|\\.sleep\\(|usleep|nanosleep|await\\s+new\\s+Promise.*setTimeout" "${FILES[@]}"

# N4: Testing Private Methods Directly
check "N4: Testing Private Methods Directly" \
    grep -En "expect\\([^)]*\\._[a-z]|assert.*\\._[a-z]|expect\\([^)]*\\.__" "${FILES[@]}"

# N5: Unawaited Async Assertions
check "N5: Unawaited Async Assertions" \
    grep -En "\\.then\\s*\\(\\s*[^)]*expect|\\.then\\s*\\(\\s*[^)]*assert" "${FILES[@]}"

printf '\n%s\n' "## SHOULD Rules"

# S1: Shared Mutable State Between Tests
warn "S1: Shared Mutable State Between Tests" \
    bash -c 'grep -l "beforeAll" "$@" 2>/dev/null | xargs -I{} sh -c '"'"'grep -l "^let\s" "{}" 2>/dev/null && echo "{}: has beforeAll with top-level let"'"'"'' _ "${FILES[@]}"

# S2: Try-Catch Swallowing Failures
warn "S2: Try-Catch Swallowing Failures" \
    bash -c 'for f in "$@"; do
  if grep -q "catch\s*(" "$f" 2>/dev/null; then
    match=$(grep -A5 "catch\s*(" "$f" | grep -E "expect|assert" | grep -v "toThrow\|rejects")
    if [[ -n "$match" ]]; then
      echo "$f: catch block contains assertions - verify not swallowing"
    fi
  fi
done' _ "${FILES[@]}"

# S3: Non-Descriptive Test Names
warn "S3: Non-Descriptive Test Names" \
    grep -En "test\\(['\"]test['\"]|test\\(['\"]works['\"]|it\\(['\"]it['\"]|it\\(['\"]test['\"]" "${FILES[@]}"

# S4: Logic in Tests
warn "S4: Logic in Tests" \
    bash -c 'grep -En "^\s+(if|for|while)\s*\(" "$@" | grep -v "forEach\|test\.each\|pytest\.mark"' _ "${FILES[@]}"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
