#!/usr/bin/env bash
# webhooks.validate.sh - Outbound event notification design
# Generated by flight-domain-compile from webhooks.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="**/webhook*.js **/webhook*.ts **/hooks/**/*.js **/hooks/**/*.ts **/*Webhook*.java **/webhooks.py **/webhook_handler*.py"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -10 | sed 's/^/   /') || true
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -5 | sed 's/^/   /') || true
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  WEBHOOKS Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "webhook*.js" "webhook*.ts" "*.js" "*.ts" "*Webhook*.java" "webhooks.py" "webhook_handler*.py")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    # Redirect stdin from /dev/null to prevent hanging in piped contexts (curl | bash)
    mapfile -t FILES < <(find . -type f \( -name "webhook*.js" -o -name "webhook*.ts" -o -name "*.js" -o -name "*.ts" -o -name "*Webhook*.java" -o -name "webhooks.py" -o -name "webhook_handler*.py" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" < /dev/null 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: **/webhook*.js **/webhook*.ts **/hooks/**/*.js **/hooks/**/*..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: Plain HTTP Webhook URLs
check "N1: Plain HTTP Webhook URLs" \
    bash -c 'for file in "$@"; do
grep -Ein "webhook.*http://[^l]|http://.*webhook" "$@" | grep -v "localhost\|127\.0\.0\.1"
done' _ "${FILES[@]}"

# N2: Secrets in Webhook Payloads
check "N2: Secrets in Webhook Payloads" \
    # Unknown check type: ast

# N3: Unsafe Signature Comparison
check "N3: Unsafe Signature Comparison" \
    # Unknown check type: ast

# N4: Unsafe Signature .equals() Call
check "N4: Unsafe Signature .equals() Call" \
    # Unknown check type: ast

# N5: Infinite Retry - while(true)
check "N5: Infinite Retry - while(true)" \
    # Unknown check type: ast

# N6: Infinite Retry - for(;;)
check "N6: Infinite Retry - for(;;)" \
    # Unknown check type: ast

# N7: Non-HTTPS URL Schemes
check "N7: Non-HTTPS URL Schemes" \
    # Unknown check type: ast

printf '\n%s\n' "## SHOULD Rules"

# S1: Signature Verification Present
warn "S1: Signature Verification Present" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  if grep -qEi "webhook|hook" "$f" 2>/dev/null; then
    if ! grep -qEi "signature|hmac|verify|x-.*-signature|createHmac|hash_hmac" "$f" 2>/dev/null; then
      echo "$f: webhook handler without signature verification"
    fi
  fi
done
done' _ "${FILES[@]}"

# S2: Async Processing
warn "S2: Async Processing" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  if grep -qEi "await.*process|await.*handle|await.*save.*res\.(send|status|json)" "$f" 2>/dev/null; then
    if ! grep -qEi "queue|enqueue|publish|dispatch|bull|sqs|rabbitmq|kafka" "$f" 2>/dev/null; then
      echo "$f: possible sync processing before response"
    fi
  fi
done
done' _ "${FILES[@]}"

# S3: Idempotency Handling
warn "S3: Idempotency Handling" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  if grep -qEi "webhook|hook" "$f" 2>/dev/null; then
    if ! grep -qEi "idempoten|delivery.?id|webhook.?id|x-.*-id|dedup|already.?processed" "$f" 2>/dev/null; then
      echo "$f: no idempotency handling detected"
    fi
  fi
done
done' _ "${FILES[@]}"

# S4: URL/IP Validation for SSRF Prevention
warn "S4: URL/IP Validation for SSRF Prevention" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  if grep -qEi "webhook.*url|url.*webhook|register.*hook|endpoint" "$f" 2>/dev/null; then
    if ! grep -qEi "isPrivate|privateIP|private.*range|internal.*ip|isValidUrl|validateUrl|blockList|allowList|dns\.resolve|dns\.lookup" "$f" 2>/dev/null; then
      echo "$f: webhook URL handling without IP validation"
    fi
  fi
done
done' _ "${FILES[@]}"

# S5: Event Type Handling
warn "S5: Event Type Handling" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  if grep -qEi "webhook|hook" "$f" 2>/dev/null; then
    if ! grep -qEi "event.?type|event_type|eventType|\.type|\.event|x-.*-event" "$f" 2>/dev/null; then
      echo "$f: no event type handling detected"
    fi
  fi
done
done' _ "${FILES[@]}"

# S6: Timestamp Handling
warn "S6: Timestamp Handling" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  if grep -qEi "webhook|hook" "$f" 2>/dev/null; then
    if ! grep -qEi "timestamp|created.?at|x-.*-timestamp|time" "$f" 2>/dev/null; then
      echo "$f: no timestamp handling detected"
    fi
  fi
done
done' _ "${FILES[@]}"

# S7: HMAC Signature Implementation
warn "S7: HMAC Signature Implementation" \
    bash -c 'for file in "$@"; do
grep -qEi "createHmac|hash_hmac|hmac\.new|HMACSHA|HmacUtils" "$@" || echo "No HMAC implementation detected"
done' _ "${FILES[@]}"

# S8: Proper Response Codes
warn "S8: Proper Response Codes" \
    bash -c 'for file in "$@"; do
grep -qEi "status\(200\)|status\(202\)|sendStatus\(200\)|\.ok\(|res\.send\(" "$@" || echo "No 2xx response handling detected"
done' _ "${FILES[@]}"

# S9: Retry with Backoff Logic
warn "S9: Retry with Backoff Logic" \
    bash -c 'for file in "$@"; do
grep -qEi "backoff|retry|exponential|attempt|max.?retries" "$@" || echo "No retry/backoff logic detected"
done' _ "${FILES[@]}"

# S10: Dead Letter Queue Handling
warn "S10: Dead Letter Queue Handling" \
    bash -c 'for file in "$@"; do
grep -qEi "dead.?letter|dlq|failed.?queue|poison.?queue" "$@" || echo "No dead letter queue handling detected"
done' _ "${FILES[@]}"

# S11: Webhook URL Validation on Registration
warn "S11: Webhook URL Validation on Registration" \
    bash -c 'for file in "$@"; do
for f in "$@"; do
  if grep -qEi "register.*webhook|webhook.*register|save.*webhook.*url|add.*endpoint" "$f" 2>/dev/null; then
    if ! grep -qEi "validateUrl|isValidUrl|url.*valid|dns\.resolve|lookup|parseUrl" "$f" 2>/dev/null; then
      echo "$f: webhook registration without URL validation"
    fi
  fi
done
done' _ "${FILES[@]}"

# S12: Payload Size Limits
warn "S12: Payload Size Limits" \
    bash -c 'for file in "$@"; do
grep -qEi "payload.?size|max.?size|body.?limit|20.?kb|size.?limit" "$@" || echo "No payload size limits detected"
done' _ "${FILES[@]}"

# S13: Webhook Logging
warn "S13: Webhook Logging" \
    bash -c 'for file in "$@"; do
grep -qEi "log.*webhook|webhook.*log|logger|console\.(log|info|error).*webhook" "$@" || echo "No webhook-specific logging detected"
done' _ "${FILES[@]}"

# S14: Secret Rotation Support
warn "S14: Secret Rotation Support" \
    bash -c 'for file in "$@"; do
grep -qEi "rotate|multiple.?secret|old.?secret|new.?secret|secret.?version" "$@" || echo "No secret rotation support detected"
done' _ "${FILES[@]}"

# S15: Timing-Safe Comparison Used
warn "S15: Timing-Safe Comparison Used" \
    bash -c 'for file in "$@"; do
grep -qEi "timingSafeEqual|constant.?time|secure.?compare|MessageDigest\.isEqual|hmac\.compare" "$@" || echo "No timing-safe comparison detected"
done' _ "${FILES[@]}"

# S16: Queue Integration
warn "S16: Queue Integration" \
    bash -c 'for file in "$@"; do
grep -qEi "queue|bull|sqs|rabbitmq|kafka|redis.*publish|pub.?sub|enqueue" "$@" || echo "No queue integration detected"
done' _ "${FILES[@]}"

# S17: Schema Validation
warn "S17: Schema Validation" \
    bash -c 'for file in "$@"; do
grep -qEi "joi|zod|yup|ajv|schema.*valid|validate.*schema|json.?schema" "$@" || echo "No schema validation detected"
done' _ "${FILES[@]}"

# S18: Registration Verification Challenge
warn "S18: Registration Verification Challenge" \
    bash -c 'for file in "$@"; do
grep -qEi "challenge|verification.*webhook|webhook.*verification|verify.*endpoint|test.*webhook" "$@" || echo "No registration verification detected"
done' _ "${FILES[@]}"

# S19: Egress Proxy for Webhook Delivery
warn "S19: Egress Proxy for Webhook Delivery" \
    bash -c 'for file in "$@"; do
grep -qEi "smokescreen|egress.*proxy|webhook.*proxy|proxy.*webhook|sentry" "$@" || echo "No egress proxy detected (optional but recommended)"
done' _ "${FILES[@]}"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
