#!/usr/bin/env bash
# webhooks.validate.sh - Outbound event notification design
# Generated by flight-domain-compile from webhooks.flight
set -euo pipefail

# Script location for sourcing helpers
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Default: common file patterns
DEFAULT_PATTERNS="**/webhook*.js **/webhook*.ts **/hooks/**/*.js **/hooks/**/*.ts **/*Webhook*.java **/webhooks.py **/webhook_handler*.py"
PASS=0
FAIL=0
WARN=0

red() { printf '\033[31m%s\033[0m\n' "$1"; }
green() { printf '\033[32m%s\033[0m\n' "$1"; }
yellow() { printf '\033[33m%s\033[0m\n' "$1"; }

check() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        red "❌ $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -10 | sed 's/^/   /') || true
        ((FAIL++)) || true
    fi
}

warn() {
    local name="$1"
    shift
    local result
    result=$("$@" 2>/dev/null) || true
    if [[ -z "$result" ]]; then
        green "✅ $name"
        ((PASS++)) || true
    else
        yellow "⚠️  $name"
        # Use subshell to prevent SIGPIPE from killing script with pipefail
        (printf '%s\n' "$result" | head -5 | sed 's/^/   /') || true
        ((WARN++)) || true
    fi
}

printf '%s\n' "═══════════════════════════════════════════"
printf '%s\n' "  WEBHOOKS Domain Validation"
printf '%s\n' "═══════════════════════════════════════════"
printf '\n'

# Source exclusions helper if available
if [[ -f "$SCRIPT_DIR/../exclusions.sh" ]]; then
    source "$SCRIPT_DIR/../exclusions.sh"
    FLIGHT_HAS_EXCLUSIONS=true
else
    FLIGHT_HAS_EXCLUSIONS=false
fi

# Handle arguments or use defaults
if [[ $# -gt 0 ]]; then
    FILES=("$@")
elif [[ "$FLIGHT_HAS_EXCLUSIONS" == true ]]; then
    # Use exclusions-aware file discovery
    mapfile -t FILES < <(flight_get_files "webhook*.js" "webhook*.ts" "*.js" "*.ts" "*Webhook*.java" "webhooks.py" "webhook_handler*.py")
else
    # Fallback: use find (works on bash 3.2+, no globstar needed)
    # Redirect stdin from /dev/null to prevent hanging in piped contexts (curl | bash)
    mapfile -t FILES < <(find . -type f \( -name "webhook*.js" -o -name "webhook*.ts" -o -name "*.js" -o -name "*.ts" -o -name "*Webhook*.java" -o -name "webhooks.py" -o -name "webhook_handler*.py" \) -not -path "*/node_modules/*" -not -path "*/.git/*" -not -path "*/dist/*" -not -path "*/build/*" < /dev/null 2>/dev/null | sort)
fi

if [[ ${#FILES[@]} -eq 0 ]]; then
    yellow "No files found matching default patterns"
    printf '%s\n' "  Patterns: **/webhook*.js **/webhook*.ts **/hooks/**/*.js **/hooks/**/*..."
    printf '\n'
    green "  RESULT: SKIP (no files)"
    exit 0
fi

printf 'Files: %d\n\n' "${#FILES[@]}"

printf '\n%s\n' "## NEVER Rules"

# N1: Plain HTTP Webhook URLs
check "N1: Plain HTTP Webhook URLs" \
    bash -c '(grep -Ein "webhook.*http://[^l]|http://.*webhook" "$@" | grep -v "localhost" | grep -v "127\\.0\\.0\\.1") || true' _ "${FILES[@]}"

# N2: Secrets in Webhook Payloads
check "N2: Secrets in Webhook Payloads" \
    # Unknown check type: ast

# N3: Unsafe Signature Comparison
check "N3: Unsafe Signature Comparison" \
    # Unknown check type: ast

# N4: Unsafe Signature .equals() Call
check "N4: Unsafe Signature .equals() Call" \
    # Unknown check type: ast

# N5: Infinite Retry - while(true)
check "N5: Infinite Retry - while(true)" \
    # Unknown check type: ast

# N6: Infinite Retry - for(;;)
check "N6: Infinite Retry - for(;;)" \
    # Unknown check type: ast

# N7: Non-HTTPS URL Schemes
check "N7: Non-HTTPS URL Schemes" \
    # Unknown check type: ast

printf '\n%s\n' "## SHOULD Rules"

# S1: Signature Verification Present
warn "S1: Signature Verification Present" \
    bash -c '
for f in "$@"; do
    trigger_lines=$(grep -nE "webhook|hook" "$f" 2>/dev/null)
    if [[ -n "$trigger_lines" ]]; then
        if ! grep -qE "signature|hmac|verify|x-.*-signature|createHmac|hash_hmac" "$f" 2>/dev/null; then
            echo "$trigger_lines" | while IFS= read -r line; do
                linenum="${line%%:*}"
                echo "$f:$linenum: webhook handler without signature verification"
            done
        fi
    fi
done
' _ "${FILES[@]}"

# S3: Idempotency Handling
warn "S3: Idempotency Handling" \
    bash -c '
for f in "$@"; do
    trigger_lines=$(grep -nE "webhook|hook" "$f" 2>/dev/null)
    if [[ -n "$trigger_lines" ]]; then
        if ! grep -qE "idempoten|delivery.?id|webhook.?id|x-.*-id|dedup|already.?processed" "$f" 2>/dev/null; then
            echo "$trigger_lines" | while IFS= read -r line; do
                linenum="${line%%:*}"
                echo "$f:$linenum: no idempotency handling detected"
            done
        fi
    fi
done
' _ "${FILES[@]}"

# S4: URL/IP Validation for SSRF Prevention
warn "S4: URL/IP Validation for SSRF Prevention" \
    bash -c '
for f in "$@"; do
    trigger_lines=$(grep -nE "webhook.*url|url.*webhook|register.*hook|endpoint" "$f" 2>/dev/null)
    if [[ -n "$trigger_lines" ]]; then
        if ! grep -qE "isPrivate|privateIP|private.*range|internal.*ip|isValidUrl|validateUrl|blockList|allowList|dns\\.resolve|dns\\.lookup" "$f" 2>/dev/null; then
            echo "$trigger_lines" | while IFS= read -r line; do
                linenum="${line%%:*}"
                echo "$f:$linenum: webhook URL handling without IP validation"
            done
        fi
    fi
done
' _ "${FILES[@]}"

# S5: Event Type Handling
warn "S5: Event Type Handling" \
    bash -c '
for f in "$@"; do
    trigger_lines=$(grep -nE "webhook|hook" "$f" 2>/dev/null)
    if [[ -n "$trigger_lines" ]]; then
        if ! grep -qE "event.?type|event_type|eventType|\\.type|\\.event|x-.*-event" "$f" 2>/dev/null; then
            echo "$trigger_lines" | while IFS= read -r line; do
                linenum="${line%%:*}"
                echo "$f:$linenum: no event type handling detected"
            done
        fi
    fi
done
' _ "${FILES[@]}"

# S6: Timestamp Handling
warn "S6: Timestamp Handling" \
    bash -c '
for f in "$@"; do
    trigger_lines=$(grep -nE "webhook|hook" "$f" 2>/dev/null)
    if [[ -n "$trigger_lines" ]]; then
        if ! grep -qE "timestamp|created.?at|x-.*-timestamp|time" "$f" 2>/dev/null; then
            echo "$trigger_lines" | while IFS= read -r line; do
                linenum="${line%%:*}"
                echo "$f:$linenum: no timestamp handling detected"
            done
        fi
    fi
done
' _ "${FILES[@]}"

# S11: Webhook URL Validation on Registration
warn "S11: Webhook URL Validation on Registration" \
    bash -c '
for f in "$@"; do
    trigger_lines=$(grep -nE "register.*webhook|webhook.*register|save.*webhook.*url|add.*endpoint" "$f" 2>/dev/null)
    if [[ -n "$trigger_lines" ]]; then
        if ! grep -qE "validateUrl|isValidUrl|url.*valid|dns\\.resolve|lookup|parseUrl" "$f" 2>/dev/null; then
            echo "$trigger_lines" | while IFS= read -r line; do
                linenum="${line%%:*}"
                echo "$f:$linenum: webhook registration without URL validation"
            done
        fi
    fi
done
' _ "${FILES[@]}"

printf '\n%s\n' "═══════════════════════════════════════════"
printf '  PASS: %d  FAIL: %d  WARN: %d\n' "$PASS" "$FAIL" "$WARN"
if [[ $FAIL -eq 0 ]]; then
    green "  RESULT: PASS"
else
    red "  RESULT: FAIL"
fi
printf '%s\n' "═══════════════════════════════════════════"

exit "$FAIL"
